version: "3.9"
services:
  app:
    image: python:3.9
    container_name: rag-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb
      - qdrant
      - clearml
    command: >
      sh -c "pip install -r requirements.txt &&
             python app.py"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.2.2
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  clearml:
    image: allegroai/clearml:latest
    container_name: clearml
    ports:
      - "8080:8080"
    environment:
      - CLEARML_APISERVER=http://clearml:8080
      - CLEARML_FILES_SERVER=http://clearml:8081
      - CLEARML_WEB_SERVER=http://clearml:8080
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  qdrant_storage:
